[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "folioman-client"
version = "0.1.0"
description = "Typed asynchronous Python SDK for Folioman REST API."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "sid-146", email = "sudhanwa.kaveeshwar@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "httpx>=0.27.0",
    "pydantic>=2.7.0",
    "pydantic-settings>=2.2.0",
    "pytest-cov>=7.1.0",
]

[project.urls]
Homepage = "https://github.com/sid-146/folioman-client"
Documentation = "https://sid-146.github.io/folioman-client/"
Repository = "https://github.com/sid-146/folioman-client.git"
Issues = "https://github.com/sid-146/folioman-client/issues"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "respx>=0.21.0",
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocstrings[python]>=0.25.0",
    "build>=1.6.1",
    "twine>=7.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/folioman_client"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["src"]
